name: flutter_test2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

# Section for flutter_launcher_icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/grit_academy_mobile.png"
  web:
    genertate: true
    image_path: "web/grit_academy_mobile.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
