name: flutter_test2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/darthvader.jpg
    - assets/images/starvswars.jpg
    - assets/images/jedi.webp


  uses-material-design: true

# Section for flutter_launcher_icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/grit_academy_mobile.png"
  web:
    generate: trues
    image_path: "web/grit_academy_mobile.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
